# -*- coding: utf-8 -*-
"""Statistics &Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iSDW5KqB-bWg2EU61zigdKhOkS-yktA3
"""

import numpy as np
import pandas as pd
import seaborn as sns

df1 = pd.read_csv("/content/drive/MyDrive/train5.csv")

df1.head()

df1.tail()

df1.info()

df1.columns

cols = ['Name', 'Ticket', 'Cabin']
df1 = df1.drop(cols, axis=1)

df1.info()

df1 = df1.dropna()

df1.info()

dummies = []
cols = ['Pclass', 'Sex', 'Embarked']
for col in cols:
    dummies.append(pd.get_dummies(df1[col]))

titanic_dummies = pd.concat(dummies, axis=1)

df1 = df1.drop(['Pclass', 'Sex', 'Embarked'], axis=1)

df1.info()

df1['Age'] = df1['Age'].interpolate()

df1.info()

X = df1.values
y = df1['Survived'].values

X = np.delete(X, 1, axis=1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)